### ISSUE TITLE
Implemented your logic

### ISSUE THREAD

**Issue by jwillis0720** [oegedijk/dash_querystrings#1]
This is awesome. I saved all my components in a URL string and I'm able to serve them to interested users. Thanks for your work. 

If you have any thoughts on how to share map or plot views, that would be helpful. 

https://covid19.jordanrwillis.com/

**Comment by oegedijk** [comment]
Hi, just saw this now. But happy that it worked! 

I also implemented it in dash_oop_components here: https://github.com/oegedijk/dash_oop_components
