### ISSUE TITLE
Can this be made to work with a Flask app linked to 2 Dash apps?

### ISSUE THREAD

**Issue by rxavier** [oegedijk/dash_querystrings#3]
Hi @oegedijk! Thank you so much for your work, it's very promising.

I've tested it with one of my Dash apps and it's working flawlessly.

However, I wanted to use this functionality for [a project of mine](https://github.com/rxavier/econuy-web) which is based on a Flask app which links to 2 different Dash apps. In that case, I couldn't get the querystrings to work (the URL didn't update, and URL parameters weren't passed to components).

My workflow is a bit different, since I'm passing the Flask server to the Dash class. Then when the Flask app is created, the dashboards are added within a Flask app_context.

While moving to a pure Dash environment is viable (the projected started in Flask and then evolved to include Dash apps, which is why it has its current setup), I would need to keep both Dash apps working simultaneously. From what I've been reading ([1](https://github.com/plotly/dash/issues/188), [2](https://community.plotly.com/t/save-current-dashboard-state-as-url/23143/3)), no one has managed to make these workarounds work for multi-app setups.

So I was wondering if this is something you have faced and if you've found any solutions.

**Comment by oegedijk** [comment]
Hi @rxavier,

Glad it was helpful, and that you were able to get it to work! In terms of multi page apps with querystrings, I have not really worked with that myself, so don't have any helpful advice to share unfortunately...

Does the URL not get passed in general, or is it just in a different format? Another way of asking, is what does `Input('url', 'href')` return?

**Comment by rxavier** [comment]
I think I figured it out. It's not about the fact there's 2 Dash apps (I thought that would be, since I've seen in other threads people mentioning that limitation of other solutions similar to yours), and it's not about the main app being Flask and then Dash receiving the Flask server to piggy-back off of.

It's the use of iFrames to load Dash apps.

A bit more info:

1. I have a Flask app with a couple jinja templates that extend each other.
2. When I wanted to add a Dash dashboard, I wanted to keep my layouts (navigation bar, logo, footer, etc)
3. The only way I know how to do that is to load the Dash app into an existing HTML layout with an iFrame (https://github.com/rxavier/econuy-web/blob/master/econuy_web/templates/overview.html), where `dash_url` is the `url_base_pathname` from the `Dash` class.
4. So when I go to the URL that contains the iFrame, it doesn't match the `url_base_pathname`.
5. If I go and load the Dash app directly from the URL at `url_base_pathname` (not the URL that contains the iFrame) it works perfectly.

I think this can be explained by `dcc.Location` not being able to read the URL where the iFrame is located, but I'm not sure.

I don't know if there's a way to make my setup work. In that case, I might just have to rebuild the layout with Dash components and get rid of most of the Flask setup.

**Comment by oegedijk** [comment]
Ah, that makes some sense, yes! 

Also makes sense that an iframe wouldn't have access to certain things like the querystring of the parent frame...
